### ISSUE TITLE
Santander traffic data

### ISSUE THREAD

**Issue by tthoeye** [OrganicityEu/organicity-discovery-api#10]
We are trying to find data on traffic in Santander but are having some trouble finding these through the discovery API.

No data is available for any of the following types:

* http://discovery.organicity.eu/v0/assets?type=trafficStatus
* http://discovery.organicity.eu/v0/assets?type=iotdevice:vehiclecount
* http://discovery.organicity.eu/v0/assets?type=iotdevice:vehiclespeed
* http://discovery.organicity.eu/v0/assets?type=iotdevice:magneticLoop

However, we did find some info on magnetic loops here:

* http://discovery.organicity.eu/v0/assets?type=magneticLoop

This type name doesn't comply with what is shown on http://discovery.organicity.eu/v0/types ("iotdevice:magneticLoop" instead of "magneticLoop") - are we interpreting the type names wrongly?

**Comment by pral2a** [comment]
Hi @tthoeye we discussed this on slack also but just replying here. I will recommend you using the meta search for this kind of queries:

http://discovery.organicity.eu/v0/assets/metadata/search?query=santander+park
