### ISSUE TITLE
500 URL error, but ok when either lat or long params are removed

### ISSUE THREAD

**Issue by viktorsmari** [OrganicityEu/organicity-discovery-api#24]
This URL gives a 500 error:
https://discovery.organicity.eu/v0/assets/geo/search?km=true&lat=56.16505306859774&long=10.212821960449219&per=500&radius=32.59313012599378

Removing either **lat** or **long** params however is OK like this:
https://discovery.organicity.eu/v0/assets/geo/search?km=true&lat=56.16505306859774&per=500&radius=32.59313012599378

**Comment by viktorsmari** [comment]
It was OK before this commit:
https://github.com/OrganicityEu/organicity-discovery-api/commit/979071a28df2b649aae976ba57d49b78e7167ee2

**Comment by pral2a** [comment]
Dup https://github.com/OrganicityEu/organicity-discovery-api/issues/30
