### ISSUE TITLE
Experimenters and experiments filter doesn't work

### ISSUE THREAD

**Issue by pral2a** [OrganicityEu/organicity-discovery-api#5]
The  `/assets/experimenters/:experimenter`  and `/assets/experiments/:experiment` are not properly filtering due to a wrong regex definition on:

https://github.com/OrganicityEu/organicity-discovery-api/blob/master/lib/mongo_orion_client.rb#L47

This might also extend to other regex filters used on the same function.

## Issue example:

The regex wilcards as `/.*.62afc265-af9a-47e7-afb5-caab21ed09b4.*.*.*/` have the same effect as simply `/62afc265-af9a-47e7-afb5-caab21ed09b4/`. 

http://discovery.organicity.eu/v0/assets/experiments/62afc265-af9a-47e7-afb5-caab21ed09b4

`{:page=>1, :per=>30, :experiment=>"62afc265-af9a-47e7-afb5-caab21ed09b4"}`
`{"_id.id"=>/.*62afc265-af9a-47e7-afb5-caab21ed09b4.*.*.*.*/}`

http://discovery.organicity.eu/v0/assets/experimenters/57f3debd6ec783244b3901e2

`{:page=>1, :per=>30, :experimenter=>"57f3debd6ec783244b3901e2"}`
`{"_id.id"=>/.*.57f3debd6ec783244b3901e2.*.*.*/}`

## Regex solution
This can be solved by simply using the full experimenters asset path as `urn:oc:entity:experimenters:.*` and then using `[^:]+`  as a wildcard. Example:

Experimenters: `{"_id.id": /urn:oc:entity:experimenters:62afc265-af9a-47e7-afb5-caab21ed09b4/}`
Experiments: `{"_id.id": /urn:oc:entity:experimenters:[^:]+:57f3debd6ec783244b3901e2/}`

## The model

Just a quick reminder on the entities **urn** model:

**Experiments**

`urn:oc:entity:experimenters:{experimenterID}:{experimentID}:{assetName}`
`urn: urn:oc:entity:experimenters:62afc265-af9a-47e7-afb5-caab21ed09b4:57f3debd6ec783244b3901e2:asset56`
`experimenterID: 62afc265-af9a-47e7-afb5-caab21ed09b4`
`experimentID: 57f3debd6ec783244b3901e2`
`assetName: asset56`

**Facility**

`urn:oc:entity:{site}:{service}:{provider}:{group}:{entityName}`
*{group}: Is optional*
`urn:oc:entity:london:transportService:TransportAPI:NEH`
`site: london`
`service: transportService`
`provider: TransportAPI`
`group: none`
`assetName: NEH`

**Comment by hiromipaw** [comment]
If you change the regular expression it might become more cumbersome to combine regular expressions for sequential queries. Just a _heads up_

**Comment by pral2a** [comment]
This got fixed here https://github.com/OrganicityEu/organicity-discovery-api/commit/84c51473ed7c17c6e0c87a6fdb367aae2badbc2a
